INSERT INTO savollar (matn, variant_a, variant_b, variant_c, variant_d, togri_javob) VALUES
('bu biznes sub’ekti tomonidan amalga oshiriladigan aktivlar xarakati to’g’risida ma’lumot', '', 'bu biznes sub’ekti tomonidan amalga oshiriladigan haqiqiy operatsiyalar bo’yicha ma’lumotlar', '', '', 'bu biznes sub’ekti tomonidan amalga oshiriladigan haqiqiy operatsiyalar bo’yicha ma’lumotlar'),
('mablag'larni jalb qilish va moliyaviy resurslarni nazorat qilish', '', 'korxonaning natijalari va moliyaviy holati to'g'risida hisobot berish usuli hisoblanadi.', '', '', 'korxonaning natijalari va moliyaviy holati to'g'risida hisobot berish usuli hisoblanadi.'),
('Xom – ashyo va materiallar birinchi kirim va o‘rtacha', '', 'Birinchi kirim qilingan xom – ashyo va materiallar birinchi chiqim qilinadi.', '', '', 'Birinchi kirim qilingan xom – ashyo va materiallar birinchi chiqim qilinadi.'),
('Xom – ashyo va materiallar birinchi kirim va o‘rtacha narx bilan chiqim qilinadi', '', 'Xom – ashyo va materiallar o‘rtacha narh bo‘yicha chiqim qilinadi', '', '', 'Xom – ashyo va materiallar o‘rtacha narh bo‘yicha chiqim qilinadi'),
('Xom – ashyo va materiallar birinchi kirim va o‘rtacha narx bilan', '', 'Oxirgi kirim qilingan xom – ashyo va materiallar birinchi chiqim qilinadi', '', '', 'Oxirgi kirim qilingan xom – ashyo va materiallar birinchi chiqim qilinadi'),
('Naf keltirishi, balansga kiritish, mulk huquqi', '', 'Naf kelterishi, pulda baholanishi, mulk huquqi', '', '', 'Naf kelterishi, pulda baholanishi, mulk huquqi'),
('Xo‘jalik muomalalarini bitta schyotning debetiga yozish', '', 'Har bir xo‘jalik operatsiyasining summasi: bir schyot debetida va ayni vaqtda o‘zaro bog‘liq bo‘lgan boshqa schyotning kreditida qayd qilinishi', '', '', 'Har bir xo‘jalik operatsiyasining summasi: bir schyot debetida va ayni vaqtda o‘zaro bog‘liq bo‘lgan boshqa schyotning kreditida qayd qilinishi'),
('Korxonalar , tashkilotlar va muassasalarning xo‘jalik faoliyati amalga oshirishda foydalaniladigan resurslar samarali boshqarish uchun zarur bo‘lgan axborotlarni shakllantirish', '', 'Uzoq muddatli va joriy aktivlar, majburiyatlar, xususiy kapital, zahiralar, daromadlar va xarajatlar, foyda, zararlar hamda ularning harakati bilan bog‘liq xo‘jalik operatsiyalari', '', '', 'Uzoq muddatli va joriy aktivlar, majburiyatlar, xususiy kapital, zahiralar, daromadlar va xarajatlar, foyda, zararlar hamda ularning harakati bilan bog‘liq xo‘jalik operatsiyalari'),
('Mark Antoniy', '', 'Luka Pacholi', '', '', 'Luka Pacholi'),
('ishlab chiqarishga taalluqli asosiy vositalar', '', 'ishlab chiqarishga taalluqli asosiy vositalari va noishlab chiqarishga taalluqli asosiy vositalar', '', '', 'ishlab chiqarishga taalluqli asosiy vositalari va noishlab chiqarishga taalluqli asosiy vositalar'),
('bu operativ hisob ma'lumotlai bazasi', '', 'bu buxgalteriya hisobini yuritish va moliyaviy hisobot tuzish uchun xo’jalik yurituvchi sub’ekt qo’llaydigan usullarning jamlanmasi', '', '', 'bu buxgalteriya hisobini yuritish va moliyaviy hisobot tuzish uchun xo’jalik yurituvchi sub’ekt qo’llaydigan usullarning jamlanmasi'),
('1 yanvardan 1 yanvargacha', '', '1 yanvardan 31 dekabrgacha', '', '', '1 yanvardan 31 dekabrgacha'),
('Lotincha yozmoq', '', 'Nemischa buch-kitob, halten-tutmoq', '', '', 'Nemischa buch-kitob, halten-tutmoq'),
('Moddiy, maʻnaviy, turli', '', 'Qisqa muddatli, uzoq muddatli', '', '', 'Qisqa muddatli, uzoq muddatli'),
('Bozor qiymati', '', 'Sotib olish qiymati', '', '', 'Sotib olish qiymati'),
('Xoʻjalik yurituvchi subʻekt tasarrufidagi (foiz, royalti, dividend va ijara haqi shaklida) daromad olishga moʻljallangan, investitsiya qilingan kapital qiymatining ortishi yoki investitsiya qiluvchi kompaniyaning boshqa naf olish uchun foydalanadigan aktivlar', '', 'Muomalada boʻlish muddati 12 oydan oshmaydigan oson realizatsiya qilinadigan investitsiyalar', '', '', 'Muomalada boʻlish muddati 12 oydan oshmaydigan oson realizatsiya qilinadigan investitsiyalar'),
('Bozor qiymati boʻyicha', '', 'Xarid qiymati boʻyicha', '', '', 'Xarid qiymati boʻyicha'),
('Bozor qiymati boʻyicha', '', 'Xarid qiymati boʻyicha', '', '', 'Xarid qiymati boʻyicha'),
('Qisqa muddatli investitsiyalar oson realizatsiya boʻladigan aktivlar boʻlganligi uchun ularni hisobga olish uchun alohida schyotlar moʻljallanmagan', '', '5800 – Qisqa muddatli investitsiyalar', '', '', '5800 – Qisqa muddatli investitsiyalar'),
('AJning xususiy aktsiyalari sotib olinganida', '', 'Pul oʻtkazish yoʻli bilan qisqa muddatli qimmatli qogʻozlar xarid qilinganida', '', '', 'Pul oʻtkazish yoʻli bilan qisqa muddatli qimmatli qogʻozlar xarid qilinganida'),
('Dt 5810 - “Qimmatli qogʻozlar” schyoti; Kt 5210 - “Mamlakat ichidagi valyuta schyotlari”', '', 'Dt 5810 - “Qimmatli qogʻozlar” schyoti; Kt 5110 - “Hisob-kitob schyoti”', '', '', 'Dt 5810 - “Qimmatli qogʻozlar” schyoti; Kt 5110 - “Hisob-kitob schyoti”'),
('Dt 5820-“Berilgan qisqa muddatli qarzlar” schyoti; Kt 5210-“Mamlakt ichidagi valyuta schyotlar”', '', 'Dt 5820-“Berilgan qisqa muddatli qarzlar” schyoti; Kt 5110-“Hisob-kitob schyoti”', '', '', 'Dt 5820-“Berilgan qisqa muddatli qarzlar” schyoti; Kt 5110-“Hisob-kitob schyoti”'),
('Dt 5810-“Qimmatli qogʻozlar” schyoti; Kt 9590-“Moliyaviy faoliyatining boshqa daromadlari” schyoti', '', 'Dt 9220-“Boshqa aktivlarning chiqib ketishi” schyoti; Kt 5810-“Qimmatli qogʻozlar” schyoti', '', '', 'Dt 9220-“Boshqa aktivlarning chiqib ketishi” schyoti; Kt 5810-“Qimmatli qogʻozlar” schyoti'),
('Majburiyatlar', '', 'Joriy aktivlar', '', '', 'Joriy aktivlar'),
('5', '', '4', '', '', '4'),
('Ishlab chiqarish jarayonida kerakli xom-ashyo va materiallar', '', 'Xo’jalik yurituvchi sub’ektda keyinchalik qayta ishlashga yonaltirilgan sotib olingan yoki mustaqil ravishda tayyorlangan buyumlar', '', '', 'Xo’jalik yurituvchi sub’ektda keyinchalik qayta ishlashga yonaltirilgan sotib olingan yoki mustaqil ravishda tayyorlangan buyumlar'),
('bu kompaniyalarga, mahsulot va xizmatlarga beriladigan nomlar, belgilar va boshqa identifikatsiyalarni aniqlovchilardir', '', 'xo’jalik yurituvchi sub’ektning mulki hisoblangan uzoq muddatli moddiy ko'rinishga ega bo'lmagan aktivlardir', '', '', 'xo’jalik yurituvchi sub’ektning mulki hisoblangan uzoq muddatli moddiy ko'rinishga ega bo'lmagan aktivlardir'),
('Dalolatnoma', '', 'Schyot-faktura, shartnoma', '', '', 'Schyot-faktura, shartnoma'),
('Daromadlari', '', 'O‘z mablag‘larning tashkil topish manbalari', '', '', 'O‘z mablag‘larning tashkil topish manbalari'),
('Amortizasiya summasi hisoblash koeffisientining maxraji bo‘lgan ob'ektning xizmat muddati yig‘indisi bilan aniqlanadi', '', 'Asosiy vositani foydali ishlatishning butun davri mobaynida eskirishning doimiy summalarini hisoblab yozishdan iborat', '', '', 'Asosiy vositani foydali ishlatishning butun davri mobaynida eskirishning doimiy summalarini hisoblab yozishdan iborat'),
('Korxona ta'sis hujjatlariga asosan foyda hisobidan shakllantiriladigan rezerv kapitalidir', '', 'ta'sis hujjatida belgilangan doiradagi faoliyatni ta'minlash uchun ta'sischilarning korxona mulkiga qo‘ygan mablag‘larining yig‘indisidir', '', '', 'ta'sis hujjatida belgilangan doiradagi faoliyatni ta'minlash uchun ta'sischilarning korxona mulkiga qo‘ygan mablag‘larining yig‘indisidir'),
('valyuta va boshqa schotlaridagi mablag‘lar', '', 'kassadagi naqd pul va talab qilib olinadigan depozitlar, shuningdek bankning hisob-kitob, valyuta va boshqa schotlaridagi mablag‘lar.', '', '', 'kassadagi naqd pul va talab qilib olinadigan depozitlar, shuningdek bankning hisob-kitob, valyuta va boshqa schotlaridagi mablag‘lar.'),
('ta’sischilar o‘rtasida o‘zaro kelishilgan qiymatda', '', 'ta’minot, ishlab chiqarish, sotish', '', '', 'ta’minot, ishlab chiqarish, sotish'),
('Operativ ijara', '', 'Moliyaviy ijara, operativ ijara', '', '', 'Moliyaviy ijara, operativ ijara'),
('4000000/12*3=999999,9', '', '4000000/3=1333333.3', '', '', '4000000/3=1333333.3'),
('ombordagi tovarlar', '', 'xo’jalik yurituvchi sub’ekt ishlab chiqarish jarayonining pirovard mahsulotidir', '', '', 'xo’jalik yurituvchi sub’ekt ishlab chiqarish jarayonining pirovard mahsulotidir'),
('joriy aktivlar', '', 'uzoq muddatli va joriy aktivlar', '', '', 'uzoq muddatli va joriy aktivlar'),
('Aveco, Fifo', '', 'Aveco', '', '', 'Aveco'),
('000 000', '', '5 800 000', '', '', '5 800 000'),
('4 000 000', '', '5 800 000', '', '', '5 800 000'),
('4 000 000', '', '4 800 000', '', '', '4 800 000'),
('5 555 556', '', '6 666 667', '', '', '6 666 667'),
('5 555 556', '', '6 666 667', '', '', '6 666 667'),
('55 555 556', '', '33 333 333', '', '', '33 333 333'),
('30 000 000', '', '16 000 000', '', '', '16 000 000'),
('Uzoq muddatli majburiyatlar', '', 'uzoq muddatli va joriy majburiyatlar', '', '', 'uzoq muddatli va joriy majburiyatlar'),
('10 000 000', '', '1 500 000', '', '', '1 500 000'),
('10 000 000', '', '15 000 000', '', '', '15 000 000'),
('10 000 000', '', '15 000 000', '', '', '15 000 000'),
('30 00000', '', '15 000 000', '', '', '15 000 000'),
('16 000 000', '', '20 000 000', '', '', '20 000 000'),
('15-sonli BHMS', '', '9-sonli BHMS', '', '', '9-sonli BHMS'),
('nomoddiy aktivlar', '', 'aktivlar, joriy aktivlar', '', '', 'aktivlar, joriy aktivlar'),
('Korxona uzoq muddatli aktivi', '', 'korxonaga tegishli pul mablag’larining kelib tushishi (yoki korxonaning haqdorligi)', '', '', 'korxonaga tegishli pul mablag’larining kelib tushishi (yoki korxonaning haqdorligi)'),
('Korxona emission darmadi', '', 'korxona tomonidan to’lab berilishi kerak bo’lgan qarz majburiyati', '', '', 'korxona tomonidan to’lab berilishi kerak bo’lgan qarz majburiyati'),
('davr xarajatlariga muntazam taqsimlash va o’tkazish ko’rinishida eskirishning qiymat ifodasi', '', 'foydali xizmat muddat mobaynida aktivning amortizasiyalanadigan qiymatini asosiy vostalarning vazifasidan kelib chiqib mahsulot ish xizmatlar tannarxiga yoki davr xarajatlariga muntazam taqsimlash va o’tkazish ko’rinishida eskirishning qiymat ifodasi', '', '', 'foydali xizmat muddat mobaynida aktivning amortizasiyalanadigan qiymatini asosiy vostalarning vazifasidan kelib chiqib mahsulot ish xizmatlar tannarxiga yoki davr xarajatlariga muntazam taqsimlash va o’tkazish ko’rinishida eskirishning qiymat ifodasi'),
('davr xarajatlariga muntazam taqsimlash va o’tkazish ko’rinishida eskirishning qiymat ifodasi', '', 'asosiy vositalarning chiqib ketish buyicha kutilayotgan xarajatlarni chegirgan holda kutilayotgan foydali xizmat muddati oxirida asosiy vositalarni tugatish chog’ida olinadigan aktivlarning faraz qilinayotgan summasi', '', '', 'asosiy vositalarning chiqib ketish buyicha kutilayotgan xarajatlarni chegirgan holda kutilayotgan foydali xizmat muddati oxirida asosiy vositalarni tugatish chog’ida olinadigan aktivlarning faraz qilinayotgan summasi'),
('Tugatish qiymat', '', 'Boshlang’ich qiymat', '', '', 'Boshlang’ich qiymat'),
('Korxona hisob siyosati', '', 'Korxonada hisobdagi aktivlarini haqiqatdagi bilan solishtirish', '', '', 'Korxonada hisobdagi aktivlarini haqiqatdagi bilan solishtirish'),
('Gudwel amortizasiyasi', '', 'tashkilotning ulardan foydalanishga doir huquqlarini tasdiqlaydigan hujjatlarning mavjudligi; nomoddiy aktivlar balansda to‘g‘ri va o‘z vaqtida aks ettirilganligi.', '', '', 'tashkilotning ulardan foydalanishga doir huquqlarini tasdiqlaydigan hujjatlarning mavjudligi; nomoddiy aktivlar balansda to‘g‘ri va o‘z vaqtida aks ettirilganligi.'),
('xodimlar, direktorlar, boshqaruvchilar,korxona kasaba uyushmasi', '', 'investorlar, kreditorlar, auditorlik tashkilotlari, soliq idoralari, statistika organlari,', '', '', 'investorlar, kreditorlar, auditorlik tashkilotlari, soliq idoralari, statistika organlari,'),
('Dt nomoddiy aktiv  Kt mol yetkazib beruvchiga majburiyat paydo bo’ldi', '', 'Dt materiallar   Kt mol yetkazib beruvchiga majburiyat', '', '', 'Dt materiallar   Kt mol yetkazib beruvchiga majburiyat'),
('tadbirkorlik sub’ektlari', '', 'Qonunchilikka muvofiq buxgalteriya hisobini yuritishi shart bo’lgan muassasalar, tashkilot va korxonalar', '', '', 'Qonunchilikka muvofiq buxgalteriya hisobini yuritishi shart bo’lgan muassasalar, tashkilot va korxonalar'),
('bir yildan ortiq muddatga foydalanish uchun mo’ljallangan qimmatli qog’ozlar', '', 'uzoq foydalaniladigan (bir yildan ortiq), pulli bahoga ega bo’lgan va daromad keltiradigan, lekin moddiy ko’rinishga ega bo’lmagan obyektlar.', '', '', 'uzoq foydalaniladigan (bir yildan ortiq), pulli bahoga ega bo’lgan va daromad keltiradigan, lekin moddiy ko’rinishga ega bo’lmagan obyektlar.'),
('Aktivda', '', 'Debet', '', '', 'Debet'),
('Ushbu operatsiya natijasida hisob-kitob schyotida pul mablag’lari kamaydi va kassada shu summagaxususiy kapital  ko’paydi.', '', 'Ushbu operatsiya natijasida hisob-kitob schyotida pul mablag’lari kamaydi va kassada shu summaga ko’paydi.', '', '', 'Ushbu operatsiya natijasida hisob-kitob schyotida pul mablag’lari kamaydi va kassada shu summaga ko’paydi.'),
('5 000 000', '', '94 000', '', '', '94 000'),
('5 000 000', '', '100 000', '', '', '100 000'),
('600 000', '', '750 000 so’m', '', '', '750 000 so’m'),
('D-t – “Hisob-kitob schyoti” – 45 ming so’m K-t – “Majburiyatlar” – 45 ming so’m', '', 'D-t – “Hisob-kitob schyoti” – 45 ming so’m K-t – “Xaridorlar va buyurtmachilardan olingan bo’naklar” – 45 ming so’m', '', '', 'D-t – “Hisob-kitob schyoti” – 45 ming so’m K-t – “Xaridorlar va buyurtmachilardan olingan bo’naklar” – 45 ming so’m'),
('tarixiy qiymati bo‘yicha', '', 'aynan shunga o‘xshash asosiy vositalarning bozor qiymati bo‘yicha ularning haqiqiy ahvolini hisobga olgan holda', '', '', 'aynan shunga o‘xshash asosiy vositalarning bozor qiymati bo‘yicha ularning haqiqiy ahvolini hisobga olgan holda'),
('300 mln. so‘m', '', '200 mln. so‘m', '', '', '200 mln. so‘m'),
('300 mln. so‘m', '', '20 250 000 so’m', '', '', '20 250 000 so’m'),
('Debet 2010 – Asosiy ishlab chiqarish Kredit 2310 Yordamchi ishlab chiqarish', '', 'Debet 1010 - Materiallar Kredit 2010 – Asosiy ishlab chiqarish', '', '', 'Debet 1010 - Materiallar Kredit 2010 – Asosiy ishlab chiqarish'),
('Debet 0230 - Uskunaning jamg’arilgan eskirishi Kredit 2010 – Asosiy ishlab chiqarish', '', 'Debet 2010 – Asosiy ishlab chiqarish Kredit 0230 - Uskunaning jamg’arilgan eskirishi', '', '', 'Debet 2010 – Asosiy ishlab chiqarish Kredit 0230 - Uskunaning jamg’arilgan eskirishi'),
('Faqat ichki foydalanuvchilar', '', 'Ikki guruh: ichki va tashqi foydalanuvchilar', '', '', 'Ikki guruh: ichki va tashqi foydalanuvchilar'),
('Divident to‘landi', '', 'Hisobot yilida foyda ko‘rilmaganda rezerv kapitali hisobidan imtiyozli aksiyalar bo‘yicha dividend hisoblandi', '', '', 'Hisobot yilida foyda ko‘rilmaganda rezerv kapitali hisobidan imtiyozli aksiyalar bo‘yicha dividend hisoblandi'),
('ishchilarga ish haqi hisoblash', '', 'jismoniy shaxslardan olinadigan daromad solig‘ini hisoblash', '', '', 'jismoniy shaxslardan olinadigan daromad solig‘ini hisoblash'),
('Dt 1000 «Materiallarni hisobga olish schyotlari» Kt 6110 «Mol yetkazib beruvchilar va pudratchilarga to‘lanadigan schyotlar»', '', 'Dt 1510 «Materiallarni tayyorlash va xarid qilish» Kt 6010 «Mol yetkazib beruvchilar va pudratchilarga to‘lanadigan schyotlar»', '', '', 'Dt 1510 «Materiallarni tayyorlash va xarid qilish» Kt 6010 «Mol yetkazib beruvchilar va pudratchilarga to‘lanadigan schyotlar»'),
('150 mln. so‘m', '', '10 mln. so‘m', '', '', '10 mln. so‘m'),
('150 mln. so‘m', '', '100 mln. so‘m', '', '', '100 mln. so‘m'),
('Mablag‘lar tarkibi va joylashtirilishi, ularning manbalari bo‘yicha aks ettirish, iqtisodiy guruhlash', '', 'Korxona mablag‘i (aktivlari) va ularning manbalarini tekshirib, ro‘yxatga olish va olingan ma’lumotlarni hisob ma’lumotlari bilan solishtirish', '', '', 'Korxona mablag‘i (aktivlari) va ularning manbalarini tekshirib, ro‘yxatga olish va olingan ma’lumotlarni hisob ma’lumotlari bilan solishtirish'),
('40 500 so‘m', '', '13 500 so‘m =====', '', '', '13 500 so‘m ====='),
('12 055 so‘m', '', '12 360 so‘m', '', '', '12 360 so‘m'),
('21 600 va 40 250', '', '30 600 va 41 050', '', '', '30 600 va 41 050'),
('Buxgalteriya hisobi', '', 'Operativ (tezkor) hisob', '', '', 'Operativ (tezkor) hisob'),
('Mablag‘ manbai hisoblanib, balans aktiv tomonida', '', 'Mablag‘ turi hisoblanib, balansning aktiv tomonida', '', '', 'Mablag‘ turi hisoblanib, balansning aktiv tomonida'),
('Materiallarni tashish bo‘yicha xarajatlar', '', 'materiallar xarid qilishda foydalanilgan kredit bo‘yicha foizlar', '', '', 'materiallar xarid qilishda foydalanilgan kredit bo‘yicha foizlar'),
('3 000 ming so‘m', '', 'kredit bo‘yicha xarajatlar tovarning tannarxiga kiritilmaydi', '', '', 'kredit bo‘yicha xarajatlar tovarning tannarxiga kiritilmaydi'),
('320 000 so‘m balansdan tashqarida', '', '160 000 so‘m balansda va 160 000 so‘m balansdan tashqarida', '', '', '160 000 so‘m balansda va 160 000 so‘m balansdan tashqarida'),
('Oʻzbekiston Respublikasida naqd pulsiz hisob-kitob ishlari toʻgʻrisida Nizom', '', 'Mahsulot (ish, xizmat)larni ishlab chiqarish va sotish xarajatlarini tarkibi hamda moliyaviy natijalarni shakllantirish tartibi toʻgʻrisidagi Nizom', '', '', 'Mahsulot (ish, xizmat)larni ishlab chiqarish va sotish xarajatlarini tarkibi hamda moliyaviy natijalarni shakllantirish tartibi toʻgʻrisidagi Nizom'),
('Mahsulot ishlab chiqarish tannarxiga kiritiladigan xarajatlar, bevosita va bilvosita modddiy xarajatlar, bevosita va bilvosita mehnat xarajatlari', '', 'Mahsulot ishlab chiqarish tannarxiga kiritiladigan xarajatlar, ishlab chiqarish tannarxiga kitirilmaydigan xarajatlar, moliyaviy faoliyat xarajatlari va favqulodda zararlar', '', '', 'Mahsulot ishlab chiqarish tannarxiga kiritiladigan xarajatlar, ishlab chiqarish tannarxiga kitirilmaydigan xarajatlar, moliyaviy faoliyat xarajatlari va favqulodda zararlar'),
('D-t 0810-“Tugallanmagan qurilish” schyoti; K-t 6710-“Xodimlar bilan mehnat haqi boʻyicha hisoblashishlar” schyoti', '', 'D-t 2010-“Asosiy ishlab chiqarish” schyoti; K-t 6710-“Xodimlar bilan mehnat haqi boʻyicha hisoblashishlar” schyoti', '', '', 'D-t 2010-“Asosiy ishlab chiqarish” schyoti; K-t 6710-“Xodimlar bilan mehnat haqi boʻyicha hisoblashishlar” schyoti'),
('Bevosita va bilvosita moddiy xarajatlar', '', 'Sotish xarajatlari, boshqarish xarajatlari (maʼmuriy xarajatlar), boshqa operatsion xarajatlar va zararlar', '', '', 'Sotish xarajatlari, boshqarish xarajatlari (maʼmuriy xarajatlar), boshqa operatsion xarajatlar va zararlar'),
('D-t 0230-“Mashina va asbob-uskunalarning eskirishi”, K-t 2010 -“Asosiy ishlab chiqarish” schyoti;', '', 'D-t 2010-“Asosiy ishlab chiqarish” schyoti; K-t 0230-“Mashina va asbob-uskunalarning eskirishi”', '', '', 'D-t 2010-“Asosiy ishlab chiqarish” schyoti; K-t 0230-“Mashina va asbob-uskunalarning eskirishi”'),
('boshqa xarajatlar', '', 'mahsulot tannarxiga kiritiladigan xarajatlar', '', '', 'mahsulot tannarxiga kiritiladigan xarajatlar'),
('D-t 2010-“Asosiy ishlab chiqarish” schyoti; K-t 2810-“Ombordagi tayyor mahsulotlar”', '', 'D-t 1030-“Mashina va asbob-uskunalar”, K-t 2310-“Yordamchi ishlab chiqarish”', '', '', 'D-t 1030-“Mashina va asbob-uskunalar”, K-t 2310-“Yordamchi ishlab chiqarish”'),
('1,15', '', '1,1', '', '', '1,1'),
('vositachilik haqi', '', 'pul mablag‘larini sotuvchiga o‘tkazib berganligi uchun bankga to‘lanadigan komissiya', '', '', 'pul mablag‘larini sotuvchiga o‘tkazib berganligi uchun bankga to‘lanadigan komissiya'),
('1000, 2000, 2100, 2800, 2900, 3100, 5100', '', '1000, 1100, 1500, 1600, 2000, 2100, 2300, 2600, 2700, 2800, 2900', '', '', '1000, 1100, 1500, 1600, 2000, 2100, 2300, 2600, 2700, 2800, 2900'),
('Balans qiymati', '', 'Boshlang‘ich va tugatish qiymatidan', '', '', 'Boshlang‘ich va tugatish qiymatidan'),
('Bozor bahosidan qoldiq qiymat ayirilgan holda', '', 'Boshlang‘ich bahodan tugatish qiymati ayirilib foydali xizmat muddatiga bo‘lish orqali', '', '', 'Boshlang‘ich bahodan tugatish qiymati ayirilib foydali xizmat muddatiga bo‘lish orqali'),
('Sotib olingandagi qiymati orqali', '', 'Boshlang‘ich qiymatdan eskirish qiymati ayriladi', '', '', 'Boshlang‘ich qiymatdan eskirish qiymati ayriladi'),
('0400', '', '0110-0199', '', '', '0110-0199'),
('3', '', '4', '', '', '4'),
('Rahbar xohlaganda', '', 'Davlat qonunlari o‘zgarganda; hisobni olib borishining yangi shakllari va usullari joriy etilganda, Korxona qayta tashkil etilganda, ya’ni, qo‘shilganda yoki ajralib chiqqanda;', '', '', 'Davlat qonunlari o‘zgarganda; hisobni olib borishining yangi shakllari va usullari joriy etilganda, Korxona qayta tashkil etilganda, ya’ni, qo‘shilganda yoki ajralib chiqqanda;'),
('Erkin baho', '', 'Haqiqiy va reja tannarx', '', '', 'Haqiqiy va reja tannarx'),
('Ombordagi mahsulot', '', 'Xo‘jalik yurituvchi subyekt ishlab chiqarish jarayonining pirovard mahsuloti =====', '', '', 'Xo‘jalik yurituvchi subyekt ishlab chiqarish jarayonining pirovard mahsuloti ====='),
('Aveco, Fifo', '', 'Lifo', '', '', 'Lifo'),
('Tovarlar (ishlar, xizmatlar) uchun olingan bo‘nak aks ettirilgan', '', 'Xaridor va buyurtmachilardan ilgari olingan bo‘nakni hisobga olish (zachot) amalga oshirilgan', '', '', 'Xaridor va buyurtmachilardan ilgari olingan bo‘nakni hisobga olish (zachot) amalga oshirilgan'),
('5xil', '', '4 xil', '', '', '4 xil'),
('to‘g‘ri javob mavjud emas', '', 'majburiy sanash, tarozida tortish, o‘lchash yo‘li bilan aniqlanadi', '', '', 'majburiy sanash, tarozida tortish, o‘lchash yo‘li bilan aniqlanadi'),
('mehnat o‘lchovlari', '', 'Miqdor, pul va mehnat o‘lchovlari', '', '', 'Miqdor, pul va mehnat o‘lchovlari'),
('Majburiyatlar', '', 'Joriy aktivlar', '', '', 'Joriy aktivlar'),
('xususiy kapital qismida', '', 'balansning aktiv tomonida', '', '', 'balansning aktiv tomonida'),
('mehnat o‘lchovlari', '', 'Miqdor, pul va mehnat o‘lchovlari', '', '', 'Miqdor, pul va mehnat o‘lchovlari'),
('Tayyor mahsulot haridorlarga jo‘natildi va puli olindi', '', 'Taqsimlanmagan foyda hisobidan rezerv kapitaliga o’tkazildi', '', '', 'Taqsimlanmagan foyda hisobidan rezerv kapitaliga o’tkazildi'),
('Inventar', '', 'Jamg’arilgan foyda', '', '', 'Jamg’arilgan foyda'),
('Inventar', '', 'Rezerv kapitali', '', '', 'Rezerv kapitali'),
('taqsimlanmagan foyda', '', 'Nomoddiy aktiv', '', '', 'Nomoddiy aktiv'),
('joriy aktivlar', '', 'Uzoq muddatli va joriy aktivlar', '', '', 'Uzoq muddatli va joriy aktivlar'),
('valyuta', '', 'Ta’sischilarga ulushlar bo’yicha korxona qarzlari', '', '', 'Ta’sischilarga ulushlar bo’yicha korxona qarzlari'),
('Korxonaning uzoq muddatli aktivlarini barpo qilish maqsadiga yoʻnaltirgan va bir yildan oshiq muddatda toʻlashi kerak boʻlgan qarzi', '', '1 yildan ortiq muddatda toʻlashi kerak boʻlgan qarzi', '', '', '1 yildan ortiq muddatda toʻlashi kerak boʻlgan qarzi'),
('Korxonaning qisqa muddatli aktivlarini barpo qilish maqsadiga  yoʻnaltirgan va bir yildan oshiq muddatda toʻlashi kerak boʻlgan qarzi', '', '1 yildan kam muddatda toʻlashi kerak boʻlgan qarzi', '', '', '1 yildan kam muddatda toʻlashi kerak boʻlgan qarzi'),
('Dt 8840-“Maqsadli foydalanadigan soliq imtiyozlari”, Kt 8530-“Tekinga olingan mulk”', '', 'Dt 6410-“Byudjetga to‘lovlar bo‘yicha qarz”, Kt 8840-“Maqsadli foydalanadigan soliq imtiyozlari”', '', '', 'Dt 6410-“Byudjetga to‘lovlar bo‘yicha qarz”, Kt 8840-“Maqsadli foydalanadigan soliq imtiyozlari”'),
('Dt 1060-“Transport vositalari”, Kt 6010-“Mol yetkazib beruvchilar va pudratchilarga to‘lanadigan schyotlar”', '', 'Dt 6010-“Mol yetkazib beruvchilar va pudratchilarga to‘lanadigan schyotlar”, Kt 4310-“TMQlar uchun mol yetkazib beruvchilar va pudratchilarga berilgan bo‘naklar”', '', '', 'Dt 6010-“Mol yetkazib beruvchilar va pudratchilarga to‘lanadigan schyotlar”, Kt 4310-“TMQlar uchun mol yetkazib beruvchilar va pudratchilarga berilgan bo‘naklar”'),
('2-3 qism: Taʼrif stavkasi, taʼrif malaka', '', '3 qism: Taʼrif stavkasi, taʼrif setkasi, taʼrif malaka.', '', '', '3 qism: Taʼrif stavkasi, taʼrif setkasi, taʼrif malaka.'),
('Kunlik va soatlik', '', 'Ishbay va vaqtbay', '', '', 'Ishbay va vaqtbay'),
('Dt 5110-“Hisob-kitob schyoti”, Kt 6810-“Qisqa muddatli bank kreditlari”', '', 'Dt 6010-“Mol yetkazib beruvchilar va pudratchilarga to‘lanadigan schyotlar”, Kt 6810-“Qisqa muddatli bank kreditlari”', '', '', 'Dt 6010-“Mol yetkazib beruvchilar va pudratchilarga to‘lanadigan schyotlar”, Kt 6810-“Qisqa muddatli bank kreditlari”'),
('Dt 6310 Xaridorlar va buyurtmachilardan olingan bo‘naklar Kt 6010-“Mol yetkazib beruvchilar va pudratchilarga to‘lanadigan schyotlar”,', '', 'Dt 6010-“Mol yetkazib beruvchilar va pudratchilarga to‘lanadigan schyotlar”, Kt 4310-“TMQlar uchun mol yetkazib beruvchilar va pudratchilarga berilgan bo‘naklar”', '', '', 'Dt 6010-“Mol yetkazib beruvchilar va pudratchilarga to‘lanadigan schyotlar”, Kt 4310-“TMQlar uchun mol yetkazib beruvchilar va pudratchilarga berilgan bo‘naklar”'),
('Daromad oshdi majburiyat oshdi', '', 'aktiv ko’paydi, majburiyat paydo bo’ldi', '', '', 'aktiv ko’paydi, majburiyat paydo bo’ldi'),
('valyuta va boshqa schotlaridagi mablag‘lar', '', 'Kassadagi naqd pul va talab qilib olinadigan depozitlar, shuningdek bankning hisob-kitob, valyuta va boshqa schotlaridagi mablag‘lar.', '', '', 'Kassadagi naqd pul va talab qilib olinadigan depozitlar, shuningdek bankning hisob-kitob, valyuta va boshqa schotlaridagi mablag‘lar.'),
('ishlab chiqarish jarayonida kerakli xom-ashyo va materiallar', '', 'Debet', '', '', 'Debet'),
('moliyaviy hisob va soliqlar hisobi', '', 'Moliyaviy hisob va boshqaruv hisobi', '', '', 'Moliyaviy hisob va boshqaruv hisobi'),
('balansdan tashqari schyotlardir.', '', 'Doimiy schyotlardir.', '', '', 'Doimiy schyotlardir.'),
('12 000 ming so‘m', '', '12 800 ming so‘m', '', '', '12 800 ming so‘m'),
('qaysi biri kamroq bo‘lsa, shunisi bo‘yicha', '', 'Aynan shunday tovarlarning bozor qiymati', '', '', 'Aynan shunday tovarlarning bozor qiymati'),
('Mehnat o‘lchovidagi ma’lumotlarni;', '', 'Xo‘jalik  mablag‘lari va muomalalari haqida umumlashtirilgan ko‘rsatkichlarni;', '', '', 'Xo‘jalik  mablag‘lari va muomalalari haqida umumlashtirilgan ko‘rsatkichlarni;'),
('D-t 9910-“Yakuniy moliyaviy natija”, K-t 8720-“Jamgʻarilgan foyda (qoplanmagan zarar)”', '', 'D-t 9910-“Yakuniy moliyaviy natija”, K-T 8710-“Hisobot davrining taqsimlanmagan foydasi (qoplanmagan zarari)”', '', '', 'D-t 9910-“Yakuniy moliyaviy natija”, K-T 8710-“Hisobot davrining taqsimlanmagan foydasi (qoplanmagan zarari)”'),
('D-t 9710-“ Favquloddagi foydalar”, K-t 9910-“Yakuniy moliyaviy natija” schyoti', '', 'D-t 9910-“Yakuniy moliyaviy natija”, K-T 9410-9430-“Davr xarajatlarini hisobga oluvchi” schyoti', '', '', 'D-t 9910-“Yakuniy moliyaviy natija”, K-T 9410-9430-“Davr xarajatlarini hisobga oluvchi” schyoti'),
('D-t 9710-“ Favquloddagi foydalar”, K-t 9910-“Yakuniy moliyaviy natija”', '', 'D-t 9710-“ Favquloddagi foydalar”, K-T 9910-“Yakuniy moliyaviy natija”', '', '', 'D-t 9710-“ Favquloddagi foydalar”, K-T 9910-“Yakuniy moliyaviy natija”'),
('D-t 9910-“Yakuniy moliyaviy natija”, K-t 8720-“Jamgʻarilgan foyda (qoplanmagan zarar)”', '', 'D-t 8710-“Hisobot davrining taqsimlanmagan foydasi (qoplanmagan zarari)”, K-T 9910-“Yakuniy moliyaviy natija”', '', '', 'D-t 8710-“Hisobot davrining taqsimlanmagan foydasi (qoplanmagan zarari)”, K-T 9910-“Yakuniy moliyaviy natija”'),
('8-modda', '', '22-modda', '', '', '22-modda'),
('majburiyatlar va uzoq muddatli qarzlar', '', 'oʻz mablagʻlari manbai va majburiyatlar', '', '', 'oʻz mablagʻlari manbai va majburiyatlar'),
('saldosi haqida', '', 'asosiy vositalarning balans qiymati, ularning shu sanaga boʻlgan eskirish summasi va qoldiq qiymati', '', '', 'asosiy vositalarning balans qiymati, ularning shu sanaga boʻlgan eskirish summasi va qoldiq qiymati'),
('490-satrda', '', '480-satrda', '', '', '480-satrda'),
('passiv qismining 1chi boʻlimda', '', 'passiv qismining 2chi boʻlimda', '', '', 'passiv qismining 2chi boʻlimda'),
('Ombor mudiri hisoboti, Xususiy kapital toʻgʻrisida hisobot', '', 'Korxona balansi, moliyaviy natijalar toʻgʻrisidagi hisobot, pul oqimi toʻgʻrisida hisobot, xususiy kapital toʻgʻrisida hisobot', '', '', 'Korxona balansi, moliyaviy natijalar toʻgʻrisidagi hisobot, pul oqimi toʻgʻrisida hisobot, xususiy kapital toʻgʻrisida hisobot'),
('xoʻjalik yurituvchi subyektning moliyaviy hisoboti va hisob siyosati asoslari uchun turli asosiy muomalalar va hodisalarni tanlagani va qoʻllanilgani toʻgʻrisida maʼlumot taqdim etish', '', 'korxonaning nomi, mulkchilik shakli, yuridik manzili, boʻysunishi, STIR va korxonani bilish uchun kerak boʻlgan boshqa rekvizitlar', '', '', 'korxonaning nomi, mulkchilik shakli, yuridik manzili, boʻysunishi, STIR va korxonani bilish uchun kerak boʻlgan boshqa rekvizitlar'),
('Mahsulotni sotishdan olingan yalpi foyda bilan', '', 'Soliq toʻlangunga qadar olingan foyda va sof foyda bilan', '', '', 'Soliq toʻlangunga qadar olingan foyda va sof foyda bilan'),
('Majburiyatlar, xususiy kapital, rezervlar, daromadlar, xarajatlar', '', 'Aktivlar, majburiyatlar, xususiy kapital, rezervlar, daromadlar, xarajatlar va moliyaviy natijalar', '', '', 'Aktivlar, majburiyatlar, xususiy kapital, rezervlar, daromadlar, xarajatlar va moliyaviy natijalar'),
('Gazetada chop qilingandan keyin', '', 'Toʻzilib imzo va muhr bilan tasdiqlangandan keyin', '', '', 'Toʻzilib imzo va muhr bilan tasdiqlangandan keyin'),
('hisoblash qoidasiga binoan daromadlar, xarajatlar, xoʻjalik muomalalari va hodisalar sodir etilgan paytda buxgalteriya hisobida koʻrsatiladi', '', 'hisoblash qoidasiga binoan aktivlar, passivlar, oʻz kapitali, daromadlar, xarajatlar, xoʻjalik muomalalari va hodisalar sodir etilgan paytda buxgalteriya hisobida koʻrsatiladi', '', '', 'hisoblash qoidasiga binoan aktivlar, passivlar, oʻz kapitali, daromadlar, xarajatlar, xoʻjalik muomalalari va hodisalar sodir etilgan paytda buxgalteriya hisobida koʻrsatiladi'),
('boshqaruv yechimlarini ishlab chiqish', '', 'axborot berish, nazorat qilish, boshqaruv yechimlarini ishlab chiqish', '', '', 'axborot berish, nazorat qilish, boshqaruv yechimlarini ishlab chiqish'),
('pul koʻrinishidagi eʼlon qilingan dividendlar', '', 'gʻazna obligasiyalarini sotib olish', '', '', 'gʻazna obligasiyalarini sotib olish'),
('5', '', '2', '', '', '2'),
('Oy tugashi bilan', '', 'Hisobot yili yakuni boʻyicha', '', '', 'Hisobot yili yakuni boʻyicha'),
('“4-sonli BHMS” orqali', '', 'Mahsulot(ish, xizmatlar)ni ishlab chiqarish va sotish xarajatlari tarkibi hamda moliyaviy natijalarni shakllantirish tartibi toʻgʻrisida”gi Nizom orqali, “3-sonli BHMS” orqali', '', '', 'Mahsulot(ish, xizmatlar)ni ishlab chiqarish va sotish xarajatlari tarkibi hamda moliyaviy natijalarni shakllantirish tartibi toʻgʻrisida”gi Nizom orqali, “3-sonli BHMS” orqali'),
('STF=UF – DX + BD', '', 'STF=UF + FF – FZ', '', '', 'STF=UF + FF – FZ'),
('ikkiyoqlama yozish - buxgalteria hisobining oltin qoidasidir', '', 'ikkiyoqlama yozish usuli - bir xoʻjalik muomalasi  boʻyicha aynan bir xil summani buxgalteria hisobining ikki schyotida – birining debeti va boshqasining kreditida aks etishidir', '', '', 'ikkiyoqlama yozish usuli - bir xoʻjalik muomalasi  boʻyicha aynan bir xil summani buxgalteria hisobining ikki schyotida – birining debeti va boshqasining kreditida aks etishidir');
