INSERT INTO savollar (matn, variant_a, variant_b, variant_c, variant_d, togri_javob) VALUES
('bu biznes subвЂ™ekti tomonidan amalga oshiriladigan aktivlar xarakati toвЂ™gвЂ™risida maвЂ™lumot', '', 'bu biznes subвЂ™ekti tomonidan amalga oshiriladigan haqiqiy operatsiyalar boвЂ™yicha maвЂ™lumotlar', '', '', 'bu biznes subвЂ™ekti tomonidan amalga oshiriladigan haqiqiy operatsiyalar boвЂ™yicha maвЂ™lumotlar'),
('mablag'larni jalb qilish va moliyaviy resurslarni nazorat qilish', '', 'korxonaning natijalari va moliyaviy holati to'g'risida hisobot berish usuli hisoblanadi.', '', '', 'korxonaning natijalari va moliyaviy holati to'g'risida hisobot berish usuli hisoblanadi.'),
('Xom вЂ“ ashyo va materiallar birinchi kirim va oвЂrtacha', '', 'Birinchi kirim qilingan xom вЂ“ ashyo va materiallar birinchi chiqim qilinadi.', '', '', 'Birinchi kirim qilingan xom вЂ“ ashyo va materiallar birinchi chiqim qilinadi.'),
('Xom вЂ“ ashyo va materiallar birinchi kirim va oвЂrtacha narx bilan chiqim qilinadi', '', 'Xom вЂ“ ashyo va materiallar oвЂrtacha narh boвЂyicha chiqim qilinadi', '', '', 'Xom вЂ“ ashyo va materiallar oвЂrtacha narh boвЂyicha chiqim qilinadi'),
('Xom вЂ“ ashyo va materiallar birinchi kirim va oвЂrtacha narx bilan', '', 'Oxirgi kirim qilingan xom вЂ“ ashyo va materiallar birinchi chiqim qilinadi', '', '', 'Oxirgi kirim qilingan xom вЂ“ ashyo va materiallar birinchi chiqim qilinadi'),
('Naf keltirishi, balansga kiritish, mulk huquqi', '', 'Naf kelterishi, pulda baholanishi, mulk huquqi', '', '', 'Naf kelterishi, pulda baholanishi, mulk huquqi'),
('XoвЂjalik muomalalarini bitta schyotning debetiga yozish', '', 'Har bir xoвЂjalik operatsiyasining summasi: bir schyot debetida va ayni vaqtda oвЂzaro bogвЂliq boвЂlgan boshqa schyotning kreditida qayd qilinishi', '', '', 'Har bir xoвЂjalik operatsiyasining summasi: bir schyot debetida va ayni vaqtda oвЂzaro bogвЂliq boвЂlgan boshqa schyotning kreditida qayd qilinishi'),
('Korxonalar , tashkilotlar va muassasalarning xoвЂjalik faoliyati amalga oshirishda foydalaniladigan resurslar samarali boshqarish uchun zarur boвЂlgan axborotlarni shakllantirish', '', 'Uzoq muddatli va joriy aktivlar, majburiyatlar, xususiy kapital, zahiralar, daromadlar va xarajatlar, foyda, zararlar hamda ularning harakati bilan bogвЂliq xoвЂjalik operatsiyalari', '', '', 'Uzoq muddatli va joriy aktivlar, majburiyatlar, xususiy kapital, zahiralar, daromadlar va xarajatlar, foyda, zararlar hamda ularning harakati bilan bogвЂliq xoвЂjalik operatsiyalari'),
('Mark Antoniy', '', 'Luka Pacholi', '', '', 'Luka Pacholi'),
('ishlab chiqarishga taalluqli asosiy vositalar', '', 'ishlab chiqarishga taalluqli asosiy vositalari va noishlab chiqarishga taalluqli asosiy vositalar', '', '', 'ishlab chiqarishga taalluqli asosiy vositalari va noishlab chiqarishga taalluqli asosiy vositalar'),
('bu operativ hisob ma'lumotlai bazasi', '', 'bu buxgalteriya hisobini yuritish va moliyaviy hisobot tuzish uchun xoвЂ™jalik yurituvchi subвЂ™ekt qoвЂ™llaydigan usullarning jamlanmasi', '', '', 'bu buxgalteriya hisobini yuritish va moliyaviy hisobot tuzish uchun xoвЂ™jalik yurituvchi subвЂ™ekt qoвЂ™llaydigan usullarning jamlanmasi'),
('1 yanvardan 1 yanvargacha', '', '1 yanvardan 31 dekabrgacha', '', '', '1 yanvardan 31 dekabrgacha'),
('Lotincha yozmoq', '', 'Nemischa buch-kitob, halten-tutmoq', '', '', 'Nemischa buch-kitob, halten-tutmoq'),
('Moddiy, maК»naviy, turli', '', 'Qisqa muddatli, uzoq muddatli', '', '', 'Qisqa muddatli, uzoq muddatli'),
('Bozor qiymati', '', 'Sotib olish qiymati', '', '', 'Sotib olish qiymati'),
('XoК»jalik yurituvchi subК»ekt tasarrufidagi (foiz, royalti, dividend va ijara haqi shaklida) daromad olishga moК»ljallangan, investitsiya qilingan kapital qiymatining ortishi yoki investitsiya qiluvchi kompaniyaning boshqa naf olish uchun foydalanadigan aktivlar', '', 'Muomalada boК»lish muddati 12 oydan oshmaydigan oson realizatsiya qilinadigan investitsiyalar', '', '', 'Muomalada boК»lish muddati 12 oydan oshmaydigan oson realizatsiya qilinadigan investitsiyalar'),
('Bozor qiymati boК»yicha', '', 'Xarid qiymati boК»yicha', '', '', 'Xarid qiymati boК»yicha'),
('Bozor qiymati boК»yicha', '', 'Xarid qiymati boК»yicha', '', '', 'Xarid qiymati boК»yicha'),
('Qisqa muddatli investitsiyalar oson realizatsiya boК»ladigan aktivlar boК»lganligi uchun ularni hisobga olish uchun alohida schyotlar moК»ljallanmagan', '', '5800 вЂ“ Qisqa muddatli investitsiyalar', '', '', '5800 вЂ“ Qisqa muddatli investitsiyalar'),
('AJning xususiy aktsiyalari sotib olinganida', '', 'Pul oК»tkazish yoК»li bilan qisqa muddatli qimmatli qogК»ozlar xarid qilinganida', '', '', 'Pul oК»tkazish yoК»li bilan qisqa muddatli qimmatli qogК»ozlar xarid qilinganida'),
('Dt 5810 - вЂњQimmatli qogК»ozlarвЂќ schyoti; Kt 5210 - вЂњMamlakat ichidagi valyuta schyotlariвЂќ', '', 'Dt 5810 - вЂњQimmatli qogК»ozlarвЂќ schyoti; Kt 5110 - вЂњHisob-kitob schyotiвЂќ', '', '', 'Dt 5810 - вЂњQimmatli qogК»ozlarвЂќ schyoti; Kt 5110 - вЂњHisob-kitob schyotiвЂќ'),
('Dt 5820-вЂњBerilgan qisqa muddatli qarzlarвЂќ schyoti; Kt 5210-вЂњMamlakt ichidagi valyuta schyotlarвЂќ', '', 'Dt 5820-вЂњBerilgan qisqa muddatli qarzlarвЂќ schyoti; Kt 5110-вЂњHisob-kitob schyotiвЂќ', '', '', 'Dt 5820-вЂњBerilgan qisqa muddatli qarzlarвЂќ schyoti; Kt 5110-вЂњHisob-kitob schyotiвЂќ'),
('Dt 5810-вЂњQimmatli qogК»ozlarвЂќ schyoti; Kt 9590-вЂњMoliyaviy faoliyatining boshqa daromadlariвЂќ schyoti', '', 'Dt 9220-вЂњBoshqa aktivlarning chiqib ketishiвЂќ schyoti; Kt 5810-вЂњQimmatli qogК»ozlarвЂќ schyoti', '', '', 'Dt 9220-вЂњBoshqa aktivlarning chiqib ketishiвЂќ schyoti; Kt 5810-вЂњQimmatli qogК»ozlarвЂќ schyoti'),
('Majburiyatlar', '', 'Joriy aktivlar', '', '', 'Joriy aktivlar'),
('5', '', '4', '', '', '4'),
('Ishlab chiqarish jarayonida kerakli xom-ashyo va materiallar', '', 'XoвЂ™jalik yurituvchi subвЂ™ektda keyinchalik qayta ishlashga yonaltirilgan sotib olingan yoki mustaqil ravishda tayyorlangan buyumlar', '', '', 'XoвЂ™jalik yurituvchi subвЂ™ektda keyinchalik qayta ishlashga yonaltirilgan sotib olingan yoki mustaqil ravishda tayyorlangan buyumlar'),
('bu kompaniyalarga, mahsulot va xizmatlarga beriladigan nomlar, belgilar va boshqa identifikatsiyalarni aniqlovchilardir', '', 'xoвЂ™jalik yurituvchi subвЂ™ektning mulki hisoblangan uzoq muddatli moddiy ko'rinishga ega bo'lmagan aktivlardir', '', '', 'xoвЂ™jalik yurituvchi subвЂ™ektning mulki hisoblangan uzoq muddatli moddiy ko'rinishga ega bo'lmagan aktivlardir'),
('Dalolatnoma', '', 'Schyot-faktura, shartnoma', '', '', 'Schyot-faktura, shartnoma'),
('Daromadlari', '', 'OвЂz mablagвЂlarning tashkil topish manbalari', '', '', 'OвЂz mablagвЂlarning tashkil topish manbalari'),
('Amortizasiya summasi hisoblash koeffisientining maxraji boвЂlgan ob'ektning xizmat muddati yigвЂindisi bilan aniqlanadi', '', 'Asosiy vositani foydali ishlatishning butun davri mobaynida eskirishning doimiy summalarini hisoblab yozishdan iborat', '', '', 'Asosiy vositani foydali ishlatishning butun davri mobaynida eskirishning doimiy summalarini hisoblab yozishdan iborat'),
('Korxona ta'sis hujjatlariga asosan foyda hisobidan shakllantiriladigan rezerv kapitalidir', '', 'ta'sis hujjatida belgilangan doiradagi faoliyatni ta'minlash uchun ta'sischilarning korxona mulkiga qoвЂygan mablagвЂlarining yigвЂindisidir', '', '', 'ta'sis hujjatida belgilangan doiradagi faoliyatni ta'minlash uchun ta'sischilarning korxona mulkiga qoвЂygan mablagвЂlarining yigвЂindisidir'),
('valyuta va boshqa schotlaridagi mablagвЂlar', '', 'kassadagi naqd pul va talab qilib olinadigan depozitlar, shuningdek bankning hisob-kitob, valyuta va boshqa schotlaridagi mablagвЂlar.', '', '', 'kassadagi naqd pul va talab qilib olinadigan depozitlar, shuningdek bankning hisob-kitob, valyuta va boshqa schotlaridagi mablagвЂlar.'),
('taвЂ™sischilar oвЂrtasida oвЂzaro kelishilgan qiymatda', '', 'taвЂ™minot, ishlab chiqarish, sotish', '', '', 'taвЂ™minot, ishlab chiqarish, sotish'),
('Operativ ijara', '', 'Moliyaviy ijara, operativ ijara', '', '', 'Moliyaviy ijara, operativ ijara'),
('4000000/12*3=999999,9', '', '4000000/3=1333333.3', '', '', '4000000/3=1333333.3'),
('ombordagi tovarlar', '', 'xoвЂ™jalik yurituvchi subвЂ™ekt ishlab chiqarish jarayonining pirovard mahsulotidir', '', '', 'xoвЂ™jalik yurituvchi subвЂ™ekt ishlab chiqarish jarayonining pirovard mahsulotidir'),
('joriy aktivlar', '', 'uzoq muddatli va joriy aktivlar', '', '', 'uzoq muddatli va joriy aktivlar'),
('Aveco, Fifo', '', 'Aveco', '', '', 'Aveco'),
('000 000', '', '5 800 000', '', '', '5 800 000'),
('4 000 000', '', '5 800В 000', '', '', '5 800В 000'),
('4 000 000', '', '4 800 000', '', '', '4 800 000'),
('5 555 556', '', '6 666 667', '', '', '6 666 667'),
('5 555 556', '', '6 666 667', '', '', '6 666 667'),
('55 555 556', '', '33 333В 333', '', '', '33 333В 333'),
('30 000 000', '', '16 000 000', '', '', '16 000 000'),
('Uzoq muddatli majburiyatlar', '', 'uzoq muddatli va joriy majburiyatlar', '', '', 'uzoq muddatli va joriy majburiyatlar'),
('10 000 000', '', '1 500В 000', '', '', '1 500В 000'),
('10 000 000', '', '15 000В 000', '', '', '15 000В 000'),
('10 000 000', '', '15 000 000', '', '', '15 000 000'),
('30 00000', '', '15 000 000', '', '', '15 000 000'),
('16 000 000', '', '20 000В 000', '', '', '20 000В 000'),
('15-sonli BHMS', '', '9-sonli BHMS', '', '', '9-sonli BHMS'),
('nomoddiy aktivlar', '', 'aktivlar, joriy aktivlar', '', '', 'aktivlar, joriy aktivlar'),
('Korxona uzoq muddatli aktivi', '', 'korxonaga tegishli pul mablagвЂ™larining kelib tushishi (yoki korxonaning haqdorligi)', '', '', 'korxonaga tegishli pul mablagвЂ™larining kelib tushishi (yoki korxonaning haqdorligi)'),
('Korxona emission darmadi', '', 'korxona tomonidan toвЂ™lab berilishi kerak boвЂ™lgan qarz majburiyati', '', '', 'korxona tomonidan toвЂ™lab berilishi kerak boвЂ™lgan qarz majburiyati'),
('davr xarajatlariga muntazam taqsimlash va oвЂ™tkazish koвЂ™rinishida eskirishning qiymat ifodasi', '', 'foydali xizmat muddat mobaynida aktivning amortizasiyalanadigan qiymatini asosiy vostalarning vazifasidan kelib chiqib mahsulot ish xizmatlar tannarxiga yoki davr xarajatlariga muntazam taqsimlash va oвЂ™tkazish koвЂ™rinishida eskirishning qiymat ifodasi', '', '', 'foydali xizmat muddat mobaynida aktivning amortizasiyalanadigan qiymatini asosiy vostalarning vazifasidan kelib chiqib mahsulot ish xizmatlar tannarxiga yoki davr xarajatlariga muntazam taqsimlash va oвЂ™tkazish koвЂ™rinishida eskirishning qiymat ifodasi'),
('davr xarajatlariga muntazam taqsimlash va oвЂ™tkazish koвЂ™rinishida eskirishning qiymat ifodasi', '', 'asosiy vositalarning chiqib ketish buyicha kutilayotgan xarajatlarni chegirgan holda kutilayotgan foydali xizmat muddati oxirida asosiy vositalarni tugatish chogвЂ™ida olinadigan aktivlarning faraz qilinayotgan summasi', '', '', 'asosiy vositalarning chiqib ketish buyicha kutilayotgan xarajatlarni chegirgan holda kutilayotgan foydali xizmat muddati oxirida asosiy vositalarni tugatish chogвЂ™ida olinadigan aktivlarning faraz qilinayotgan summasi'),
('Tugatish qiymat', '', 'BoshlangвЂ™ich qiymat', '', '', 'BoshlangвЂ™ich qiymat'),
('Korxona hisob siyosati', '', 'Korxonada hisobdagi aktivlarini haqiqatdagi bilan solishtirish', '', '', 'Korxonada hisobdagi aktivlarini haqiqatdagi bilan solishtirish'),
('Gudwel amortizasiyasi', '', 'tashkilotning ulardan foydalanishga doir huquqlarini tasdiqlaydigan hujjatlarning mavjudligi; nomoddiy aktivlar balansda toвЂgвЂri va oвЂz vaqtida aks ettirilganligi.', '', '', 'tashkilotning ulardan foydalanishga doir huquqlarini tasdiqlaydigan hujjatlarning mavjudligi; nomoddiy aktivlar balansda toвЂgвЂri va oвЂz vaqtida aks ettirilganligi.'),
('xodimlar, direktorlar, boshqaruvchilar,korxona kasaba uyushmasi', '', 'investorlar, kreditorlar, auditorlik tashkilotlari, soliq idoralari, statistika organlari,', '', '', 'investorlar, kreditorlar, auditorlik tashkilotlari, soliq idoralari, statistika organlari,'),
('Dt nomoddiy aktiv  Kt mol yetkazib beruvchiga majburiyat paydo boвЂ™ldi', '', 'Dt materiallar   Kt mol yetkazib beruvchiga majburiyat', '', '', 'Dt materiallar   Kt mol yetkazib beruvchiga majburiyat'),
('tadbirkorlik subвЂ™ektlari', '', 'Qonunchilikka muvofiq buxgalteriya hisobini yuritishi shart boвЂ™lgan muassasalar, tashkilot va korxonalar', '', '', 'Qonunchilikka muvofiq buxgalteriya hisobini yuritishi shart boвЂ™lgan muassasalar, tashkilot va korxonalar'),
('bir yildan ortiq muddatga foydalanish uchun moвЂ™ljallangan qimmatli qogвЂ™ozlar', '', 'uzoq foydalaniladigan (bir yildan ortiq), pulli bahoga ega boвЂ™lgan va daromad keltiradigan, lekin moddiy koвЂ™rinishga ega boвЂ™lmagan obyektlar.', '', '', 'uzoq foydalaniladigan (bir yildan ortiq), pulli bahoga ega boвЂ™lgan va daromad keltiradigan, lekin moddiy koвЂ™rinishga ega boвЂ™lmagan obyektlar.'),
('Aktivda', '', 'Debet', '', '', 'Debet'),
('Ushbu operatsiya natijasida hisob-kitob schyotida pul mablagвЂ™lari kamaydi va kassada shu summagaxususiy kapital  koвЂ™paydi.', '', 'Ushbu operatsiya natijasida hisob-kitob schyotida pul mablagвЂ™lari kamaydi va kassada shu summaga koвЂ™paydi.', '', '', 'Ushbu operatsiya natijasida hisob-kitob schyotida pul mablagвЂ™lari kamaydi va kassada shu summaga koвЂ™paydi.'),
('5 000 000', '', '94 000', '', '', '94 000'),
('5 000 000', '', '100 000', '', '', '100 000'),
('600 000', '', '750 000 soвЂ™m', '', '', '750 000 soвЂ™m'),
('D-t вЂ“ вЂњHisob-kitob schyotiвЂќ вЂ“ 45 ming soвЂ™m K-t вЂ“ вЂњMajburiyatlarвЂќ вЂ“ 45 ming soвЂ™m', '', 'D-t вЂ“ вЂњHisob-kitob schyotiвЂќ вЂ“ 45 ming soвЂ™m K-t вЂ“ вЂњXaridorlar va buyurtmachilardan olingan boвЂ™naklarвЂќ вЂ“ 45 ming soвЂ™m', '', '', 'D-t вЂ“ вЂњHisob-kitob schyotiвЂќ вЂ“ 45 ming soвЂ™m K-t вЂ“ вЂњXaridorlar va buyurtmachilardan olingan boвЂ™naklarвЂќ вЂ“ 45 ming soвЂ™m'),
('tarixiy qiymati boвЂyicha', '', 'aynan shunga oвЂxshash asosiy vositalarning bozor qiymati boвЂyicha ularning haqiqiy ahvolini hisobga olgan holda', '', '', 'aynan shunga oвЂxshash asosiy vositalarning bozor qiymati boвЂyicha ularning haqiqiy ahvolini hisobga olgan holda'),
('300 mln. soвЂm', '', '200 mln. soвЂm', '', '', '200 mln. soвЂm'),
('300 mln. soвЂm', '', '20 250 000 soвЂ™m', '', '', '20 250 000 soвЂ™m'),
('Debet 2010 вЂ“ Asosiy ishlab chiqarish Kredit 2310 Yordamchi ishlab chiqarish', '', 'Debet 1010 - Materiallar Kredit 2010 вЂ“ Asosiy ishlab chiqarish', '', '', 'Debet 1010 - Materiallar Kredit 2010 вЂ“ Asosiy ishlab chiqarish'),
('Debet 0230 - Uskunaning jamgвЂ™arilgan eskirishi Kredit 2010 вЂ“ Asosiy ishlab chiqarish', '', 'Debet 2010 вЂ“ Asosiy ishlab chiqarish Kredit 0230 - Uskunaning jamgвЂ™arilgan eskirishi', '', '', 'Debet 2010 вЂ“ Asosiy ishlab chiqarish Kredit 0230 - Uskunaning jamgвЂ™arilgan eskirishi'),
('Faqat ichki foydalanuvchilar', '', 'Ikki guruh: ichki va tashqi foydalanuvchilar', '', '', 'Ikki guruh: ichki va tashqi foydalanuvchilar'),
('Divident toвЂlandi', '', 'Hisobot yilida foyda koвЂrilmaganda rezerv kapitali hisobidan imtiyozli aksiyalar boвЂyicha dividend hisoblandi', '', '', 'Hisobot yilida foyda koвЂrilmaganda rezerv kapitali hisobidan imtiyozli aksiyalar boвЂyicha dividend hisoblandi'),
('ishchilarga ish haqi hisoblash', '', 'jismoniy shaxslardan olinadigan daromad soligвЂini hisoblash', '', '', 'jismoniy shaxslardan olinadigan daromad soligвЂini hisoblash'),
('Dt 1000 В«Materiallarni hisobga olish schyotlariВ» Kt 6110 В«Mol yetkazib beruvchilar va pudratchilarga toвЂlanadigan schyotlarВ»', '', 'Dt 1510 В«Materiallarni tayyorlash va xarid qilishВ» Kt 6010 В«Mol yetkazib beruvchilar va pudratchilarga toвЂlanadigan schyotlarВ»', '', '', 'Dt 1510 В«Materiallarni tayyorlash va xarid qilishВ» Kt 6010 В«Mol yetkazib beruvchilar va pudratchilarga toвЂlanadigan schyotlarВ»'),
('150 mln. soвЂm', '', '10 mln. soвЂm', '', '', '10 mln. soвЂm'),
('150 mln. soвЂm', '', '100 mln. soвЂm', '', '', '100 mln. soвЂm'),
('MablagвЂlar tarkibi va joylashtirilishi, ularning manbalari boвЂyicha aks ettirish, iqtisodiy guruhlash', '', 'Korxona mablagвЂi (aktivlari) va ularning manbalarini tekshirib, roвЂyxatga olish va olingan maвЂ™lumotlarni hisob maвЂ™lumotlari bilan solishtirish', '', '', 'Korxona mablagвЂi (aktivlari) va ularning manbalarini tekshirib, roвЂyxatga olish va olingan maвЂ™lumotlarni hisob maвЂ™lumotlari bilan solishtirish'),
('40 500 soвЂm', '', '13 500 soвЂm =====', '', '', '13 500 soвЂm ====='),
('12 055 soвЂm', '', '12 360 soвЂm', '', '', '12 360 soвЂm'),
('21 600 va 40 250', '', '30 600 va 41 050', '', '', '30 600 va 41 050'),
('Buxgalteriya hisobi', '', 'Operativ (tezkor) hisob', '', '', 'Operativ (tezkor) hisob'),
('MablagвЂ manbai hisoblanib, balans aktiv tomonida', '', 'MablagвЂ turi hisoblanib, balansning aktiv tomonida', '', '', 'MablagвЂ turi hisoblanib, balansning aktiv tomonida'),
('Materiallarni tashish boвЂyicha xarajatlar', '', 'materiallar xarid qilishda foydalanilgan kredit boвЂyicha foizlar', '', '', 'materiallar xarid qilishda foydalanilgan kredit boвЂyicha foizlar'),
('3 000 ming soвЂm', '', 'kredit boвЂyicha xarajatlar tovarning tannarxiga kiritilmaydi', '', '', 'kredit boвЂyicha xarajatlar tovarning tannarxiga kiritilmaydi'),
('320 000 soвЂm balansdan tashqarida', '', '160 000 soвЂm balansda va 160 000 soвЂm balansdan tashqarida', '', '', '160 000 soвЂm balansda va 160 000 soвЂm balansdan tashqarida'),
('OК»zbekiston Respublikasida naqd pulsiz hisob-kitob ishlari toК»gК»risida Nizom', '', 'Mahsulot (ish, xizmat)larni ishlab chiqarish va sotish xarajatlarini tarkibi hamda moliyaviy natijalarni shakllantirish tartibi toК»gК»risidagi Nizom', '', '', 'Mahsulot (ish, xizmat)larni ishlab chiqarish va sotish xarajatlarini tarkibi hamda moliyaviy natijalarni shakllantirish tartibi toК»gК»risidagi Nizom'),
('Mahsulot ishlab chiqarish tannarxiga kiritiladigan xarajatlar, bevosita va bilvosita modddiy xarajatlar, bevosita va bilvosita mehnat xarajatlari', '', 'Mahsulot ishlab chiqarish tannarxiga kiritiladigan xarajatlar, ishlab chiqarish tannarxiga kitirilmaydigan xarajatlar, moliyaviy faoliyat xarajatlari va favqulodda zararlar', '', '', 'Mahsulot ishlab chiqarish tannarxiga kiritiladigan xarajatlar, ishlab chiqarish tannarxiga kitirilmaydigan xarajatlar, moliyaviy faoliyat xarajatlari va favqulodda zararlar'),
('D-t 0810-вЂњTugallanmagan qurilishвЂќ schyoti; K-t 6710-вЂњXodimlar bilan mehnat haqi boК»yicha hisoblashishlarвЂќ schyoti', '', 'D-t 2010-вЂњAsosiy ishlab chiqarishвЂќ schyoti; K-t 6710-вЂњXodimlar bilan mehnat haqi boК»yicha hisoblashishlarвЂќ schyoti', '', '', 'D-t 2010-вЂњAsosiy ishlab chiqarishвЂќ schyoti; K-t 6710-вЂњXodimlar bilan mehnat haqi boК»yicha hisoblashishlarвЂќ schyoti'),
('Bevosita va bilvosita moddiy xarajatlar', '', 'Sotish xarajatlari, boshqarish xarajatlari (maКјmuriy xarajatlar), boshqa operatsion xarajatlar va zararlar', '', '', 'Sotish xarajatlari, boshqarish xarajatlari (maКјmuriy xarajatlar), boshqa operatsion xarajatlar va zararlar'),
('D-t 0230-вЂњMashina va asbob-uskunalarning eskirishiвЂќ, K-t 2010 -вЂњAsosiy ishlab chiqarishвЂќ schyoti;', '', 'D-t 2010-вЂњAsosiy ishlab chiqarishвЂќ schyoti; K-t 0230-вЂњMashina va asbob-uskunalarning eskirishiвЂќ', '', '', 'D-t 2010-вЂњAsosiy ishlab chiqarishвЂќ schyoti; K-t 0230-вЂњMashina va asbob-uskunalarning eskirishiвЂќ'),
('boshqa xarajatlar', '', 'mahsulot tannarxiga kiritiladigan xarajatlar', '', '', 'mahsulot tannarxiga kiritiladigan xarajatlar'),
('D-t 2010-вЂњAsosiy ishlab chiqarishвЂќ schyoti; K-t 2810-вЂњOmbordagi tayyor mahsulotlarвЂќ', '', 'D-t 1030-вЂњMashina va asbob-uskunalarвЂќ, K-t 2310-вЂњYordamchi ishlab chiqarishвЂќ', '', '', 'D-t 1030-вЂњMashina va asbob-uskunalarвЂќ, K-t 2310-вЂњYordamchi ishlab chiqarishвЂќ'),
('1,15', '', '1,1', '', '', '1,1'),
('vositachilik haqi', '', 'pul mablagвЂlarini sotuvchiga oвЂtkazib berganligi uchun bankga toвЂlanadigan komissiya', '', '', 'pul mablagвЂlarini sotuvchiga oвЂtkazib berganligi uchun bankga toвЂlanadigan komissiya'),
('1000, 2000, 2100, 2800, 2900, 3100, 5100', '', '1000, 1100, 1500, 1600, 2000, 2100, 2300, 2600, 2700, 2800, 2900', '', '', '1000, 1100, 1500, 1600, 2000, 2100, 2300, 2600, 2700, 2800, 2900'),
('Balans qiymati', '', 'BoshlangвЂich va tugatish qiymatidan', '', '', 'BoshlangвЂich va tugatish qiymatidan'),
('Bozor bahosidan qoldiq qiymat ayirilgan holda', '', 'BoshlangвЂich bahodan tugatish qiymati ayirilib foydali xizmat muddatiga boвЂlish orqali', '', '', 'BoshlangвЂich bahodan tugatish qiymati ayirilib foydali xizmat muddatiga boвЂlish orqali'),
('Sotib olingandagi qiymati orqali', '', 'BoshlangвЂich qiymatdan eskirish qiymati ayriladi', '', '', 'BoshlangвЂich qiymatdan eskirish qiymati ayriladi'),
('0400', '', '0110-0199', '', '', '0110-0199'),
('3', '', '4', '', '', '4'),
('Rahbar xohlaganda', '', 'Davlat qonunlari oвЂzgarganda; hisobni olib borishining yangi shakllari va usullari joriy etilganda, Korxona qayta tashkil etilganda, yaвЂ™ni, qoвЂshilganda yoki ajralib chiqqanda;', '', '', 'Davlat qonunlari oвЂzgarganda; hisobni olib borishining yangi shakllari va usullari joriy etilganda, Korxona qayta tashkil etilganda, yaвЂ™ni, qoвЂshilganda yoki ajralib chiqqanda;'),
('Erkin baho', '', 'Haqiqiy va reja tannarx', '', '', 'Haqiqiy va reja tannarx'),
('Ombordagi mahsulot', '', 'XoвЂjalik yurituvchi subyekt ishlab chiqarish jarayonining pirovard mahsuloti =====', '', '', 'XoвЂjalik yurituvchi subyekt ishlab chiqarish jarayonining pirovard mahsuloti ====='),
('Aveco, Fifo', '', 'Lifo', '', '', 'Lifo'),
('Tovarlar (ishlar, xizmatlar) uchun olingan boвЂnak aks ettirilgan', '', 'Xaridor va buyurtmachilardan ilgari olingan boвЂnakni hisobga olish (zachot) amalga oshirilgan', '', '', 'Xaridor va buyurtmachilardan ilgari olingan boвЂnakni hisobga olish (zachot) amalga oshirilgan'),
('5xil', '', '4 xil', '', '', '4 xil'),
('toвЂgвЂri javob mavjud emas', '', 'majburiy sanash, tarozida tortish, oвЂlchash yoвЂli bilan aniqlanadi', '', '', 'majburiy sanash, tarozida tortish, oвЂlchash yoвЂli bilan aniqlanadi'),
('mehnat oвЂlchovlari', '', 'Miqdor, pul va mehnat oвЂlchovlari', '', '', 'Miqdor, pul va mehnat oвЂlchovlari'),
('Majburiyatlar', '', 'Joriy aktivlar', '', '', 'Joriy aktivlar'),
('xususiy kapital qismida', '', 'balansning aktiv tomonida', '', '', 'balansning aktiv tomonida'),
('mehnat oвЂlchovlari', '', 'Miqdor, pul va mehnat oвЂlchovlari', '', '', 'Miqdor, pul va mehnat oвЂlchovlari'),
('Tayyor mahsulot haridorlarga joвЂnatildi va puli olindi', '', 'Taqsimlanmagan foyda hisobidan rezerv kapitaliga oвЂ™tkazildi', '', '', 'Taqsimlanmagan foyda hisobidan rezerv kapitaliga oвЂ™tkazildi'),
('Inventar', '', 'JamgвЂ™arilgan foyda', '', '', 'JamgвЂ™arilgan foyda'),
('Inventar', '', 'Rezerv kapitali', '', '', 'Rezerv kapitali'),
('taqsimlanmagan foyda', '', 'Nomoddiy aktiv', '', '', 'Nomoddiy aktiv'),
('joriy aktivlar', '', 'Uzoq muddatli va joriy aktivlar', '', '', 'Uzoq muddatli va joriy aktivlar'),
('valyuta', '', 'TaвЂ™sischilarga ulushlar boвЂ™yicha korxona qarzlari', '', '', 'TaвЂ™sischilarga ulushlar boвЂ™yicha korxona qarzlari'),
('Korxonaning uzoq muddatli aktivlarini barpo qilish maqsadiga yoК»naltirgan va bir yildan oshiq muddatda toК»lashi kerak boК»lgan qarzi', '', '1 yildan ortiq muddatda toК»lashi kerak boК»lgan qarzi', '', '', '1 yildan ortiq muddatda toК»lashi kerak boК»lgan qarzi'),
('Korxonaning qisqa muddatli aktivlarini barpo qilish maqsadiga  yoК»naltirgan va bir yildan oshiq muddatda toК»lashi kerak boК»lgan qarzi', '', '1 yildan kam muddatda toК»lashi kerak boК»lgan qarzi', '', '', '1 yildan kam muddatda toК»lashi kerak boК»lgan qarzi'),
('Dt 8840-вЂњMaqsadli foydalanadigan soliq imtiyozlariвЂќ, Kt 8530-вЂњTekinga olingan mulkвЂќ', '', 'Dt 6410-вЂњByudjetga toвЂlovlar boвЂyicha qarzвЂќ, Kt 8840-вЂњMaqsadli foydalanadigan soliq imtiyozlariвЂќ', '', '', 'Dt 6410-вЂњByudjetga toвЂlovlar boвЂyicha qarzвЂќ, Kt 8840-вЂњMaqsadli foydalanadigan soliq imtiyozlariвЂќ'),
('Dt 1060-вЂњTransport vositalariвЂќ, Kt 6010-вЂњMol yetkazib beruvchilar va pudratchilarga toвЂlanadigan schyotlarвЂќ', '', 'Dt 6010-вЂњMol yetkazib beruvchilar va pudratchilarga toвЂlanadigan schyotlarвЂќ, Kt 4310-вЂњTMQlar uchun mol yetkazib beruvchilar va pudratchilarga berilgan boвЂnaklarвЂќ', '', '', 'Dt 6010-вЂњMol yetkazib beruvchilar va pudratchilarga toвЂlanadigan schyotlarвЂќ, Kt 4310-вЂњTMQlar uchun mol yetkazib beruvchilar va pudratchilarga berilgan boвЂnaklarвЂќ'),
('2-3 qism: TaКјrif stavkasi, taКјrif malaka', '', '3 qism: TaКјrif stavkasi, taКјrif setkasi, taКјrif malaka.', '', '', '3 qism: TaКјrif stavkasi, taКјrif setkasi, taКјrif malaka.'),
('Kunlik va soatlik', '', 'Ishbay va vaqtbay', '', '', 'Ishbay va vaqtbay'),
('Dt 5110-вЂњHisob-kitob schyotiвЂќ, Kt 6810-вЂњQisqa muddatli bank kreditlariвЂќ', '', 'Dt 6010-вЂњMol yetkazib beruvchilar va pudratchilarga toвЂlanadigan schyotlarвЂќ, Kt 6810-вЂњQisqa muddatli bank kreditlariвЂќ', '', '', 'Dt 6010-вЂњMol yetkazib beruvchilar va pudratchilarga toвЂlanadigan schyotlarвЂќ, Kt 6810-вЂњQisqa muddatli bank kreditlariвЂќ'),
('Dt 6310 Xaridorlar va buyurtmachilardan olingan boвЂnaklar Kt 6010-вЂњMol yetkazib beruvchilar va pudratchilarga toвЂlanadigan schyotlarвЂќ,', '', 'Dt 6010-вЂњMol yetkazib beruvchilar va pudratchilarga toвЂlanadigan schyotlarвЂќ, Kt 4310-вЂњTMQlar uchun mol yetkazib beruvchilar va pudratchilarga berilgan boвЂnaklarвЂќ', '', '', 'Dt 6010-вЂњMol yetkazib beruvchilar va pudratchilarga toвЂlanadigan schyotlarвЂќ, Kt 4310-вЂњTMQlar uchun mol yetkazib beruvchilar va pudratchilarga berilgan boвЂnaklarвЂќ'),
('Daromad oshdi majburiyat oshdi', '', 'aktiv koвЂ™paydi, majburiyat paydo boвЂ™ldi', '', '', 'aktiv koвЂ™paydi, majburiyat paydo boвЂ™ldi'),
('valyuta va boshqa schotlaridagi mablagвЂlar', '', 'Kassadagi naqd pul va talab qilib olinadigan depozitlar, shuningdek bankning hisob-kitob, valyuta va boshqa schotlaridagi mablagвЂlar.', '', '', 'Kassadagi naqd pul va talab qilib olinadigan depozitlar, shuningdek bankning hisob-kitob, valyuta va boshqa schotlaridagi mablagвЂlar.'),
('ishlab chiqarish jarayonida kerakli xom-ashyo va materiallar', '', 'Debet', '', '', 'Debet'),
('moliyaviy hisob va soliqlar hisobi', '', 'Moliyaviy hisob va boshqaruv hisobi', '', '', 'Moliyaviy hisob va boshqaruv hisobi'),
('balansdan tashqari schyotlardir.', '', 'Doimiy schyotlardir.', '', '', 'Doimiy schyotlardir.'),
('12 000 ming soвЂm', '', '12 800 ming soвЂm', '', '', '12 800 ming soвЂm'),
('qaysi biri kamroq boвЂlsa, shunisi boвЂyicha', '', 'Aynan shunday tovarlarning bozor qiymati', '', '', 'Aynan shunday tovarlarning bozor qiymati'),
('Mehnat oвЂlchovidagi maвЂ™lumotlarni;', '', 'XoвЂjalik  mablagвЂlari va muomalalari haqida umumlashtirilgan koвЂrsatkichlarni;', '', '', 'XoвЂjalik  mablagвЂlari va muomalalari haqida umumlashtirilgan koвЂrsatkichlarni;'),
('D-t 9910-вЂњYakuniy moliyaviy natijaвЂќ, K-t 8720-вЂњJamgК»arilgan foyda (qoplanmagan zarar)вЂќ', '', 'D-t 9910-вЂњYakuniy moliyaviy natijaвЂќ, K-T 8710-вЂњHisobot davrining taqsimlanmagan foydasi (qoplanmagan zarari)вЂќ', '', '', 'D-t 9910-вЂњYakuniy moliyaviy natijaвЂќ, K-T 8710-вЂњHisobot davrining taqsimlanmagan foydasi (qoplanmagan zarari)вЂќ'),
('D-t 9710-вЂњ Favquloddagi foydalarвЂќ, K-t 9910-вЂњYakuniy moliyaviy natijaвЂќ schyoti', '', 'D-t 9910-вЂњYakuniy moliyaviy natijaвЂќ, K-T 9410-9430-вЂњDavr xarajatlarini hisobga oluvchiвЂќ schyoti', '', '', 'D-t 9910-вЂњYakuniy moliyaviy natijaвЂќ, K-T 9410-9430-вЂњDavr xarajatlarini hisobga oluvchiвЂќ schyoti'),
('D-t 9710-вЂњ Favquloddagi foydalarвЂќ, K-t 9910-вЂњYakuniy moliyaviy natijaвЂќ', '', 'D-t 9710-вЂњ Favquloddagi foydalarвЂќ, K-T 9910-вЂњYakuniy moliyaviy natijaвЂќ', '', '', 'D-t 9710-вЂњ Favquloddagi foydalarвЂќ, K-T 9910-вЂњYakuniy moliyaviy natijaвЂќ'),
('D-t 9910-вЂњYakuniy moliyaviy natijaвЂќ, K-t 8720-вЂњJamgК»arilgan foyda (qoplanmagan zarar)вЂќ', '', 'D-t 8710-вЂњHisobot davrining taqsimlanmagan foydasi (qoplanmagan zarari)вЂќ, K-T 9910-вЂњYakuniy moliyaviy natijaвЂќ', '', '', 'D-t 8710-вЂњHisobot davrining taqsimlanmagan foydasi (qoplanmagan zarari)вЂќ, K-T 9910-вЂњYakuniy moliyaviy natijaвЂќ'),
('8-modda', '', '22-modda', '', '', '22-modda'),
('majburiyatlar va uzoq muddatli qarzlar', '', 'oК»z mablagК»lari manbai va majburiyatlar', '', '', 'oК»z mablagК»lari manbai va majburiyatlar'),
('saldosi haqida', '', 'asosiy vositalarning balans qiymati, ularning shu sanaga boК»lgan eskirish summasi va qoldiq qiymati', '', '', 'asosiy vositalarning balans qiymati, ularning shu sanaga boК»lgan eskirish summasi va qoldiq qiymati'),
('490-satrda', '', '480-satrda', '', '', '480-satrda'),
('passiv qismining 1chi boК»limda', '', 'passiv qismining 2chi boК»limda', '', '', 'passiv qismining 2chi boК»limda'),
('Ombor mudiri hisoboti, Xususiy kapital toК»gК»risida hisobot', '', 'Korxona balansi, moliyaviy natijalar toК»gК»risidagi hisobot, pul oqimi toК»gК»risida hisobot, xususiy kapital toК»gК»risida hisobot', '', '', 'Korxona balansi, moliyaviy natijalar toК»gК»risidagi hisobot, pul oqimi toК»gК»risida hisobot, xususiy kapital toК»gК»risida hisobot'),
('xoК»jalik yurituvchi subyektning moliyaviy hisoboti va hisob siyosati asoslari uchun turli asosiy muomalalar va hodisalarni tanlagani va qoК»llanilgani toК»gК»risida maКјlumot taqdim etish', '', 'korxonaning nomi, mulkchilik shakli, yuridik manzili, boК»ysunishi, STIR va korxonani bilish uchun kerak boК»lgan boshqa rekvizitlar', '', '', 'korxonaning nomi, mulkchilik shakli, yuridik manzili, boК»ysunishi, STIR va korxonani bilish uchun kerak boК»lgan boshqa rekvizitlar'),
('Mahsulotni sotishdan olingan yalpi foyda bilan', '', 'Soliq toК»langunga qadar olingan foyda va sof foyda bilan', '', '', 'Soliq toК»langunga qadar olingan foyda va sof foyda bilan'),
('Majburiyatlar, xususiy kapital, rezervlar, daromadlar, xarajatlar', '', 'Aktivlar, majburiyatlar, xususiy kapital, rezervlar, daromadlar, xarajatlar va moliyaviy natijalar', '', '', 'Aktivlar, majburiyatlar, xususiy kapital, rezervlar, daromadlar, xarajatlar va moliyaviy natijalar'),
('Gazetada chop qilingandan keyin', '', 'ToК»zilib imzo va muhr bilan tasdiqlangandan keyin', '', '', 'ToК»zilib imzo va muhr bilan tasdiqlangandan keyin'),
('hisoblash qoidasiga binoan daromadlar, xarajatlar, xoК»jalik muomalalari va hodisalar sodir etilgan paytda buxgalteriya hisobida koК»rsatiladi', '', 'hisoblash qoidasiga binoan aktivlar, passivlar, oК»z kapitali, daromadlar, xarajatlar, xoК»jalik muomalalari va hodisalar sodir etilgan paytda buxgalteriya hisobida koК»rsatiladi', '', '', 'hisoblash qoidasiga binoan aktivlar, passivlar, oК»z kapitali, daromadlar, xarajatlar, xoК»jalik muomalalari va hodisalar sodir etilgan paytda buxgalteriya hisobida koК»rsatiladi'),
('boshqaruv yechimlarini ishlab chiqish', '', 'axborot berish, nazorat qilish, boshqaruv yechimlarini ishlab chiqish', '', '', 'axborot berish, nazorat qilish, boshqaruv yechimlarini ishlab chiqish'),
('pul koК»rinishidagi eКјlon qilingan dividendlar', '', 'gК»azna obligasiyalarini sotib olish', '', '', 'gК»azna obligasiyalarini sotib olish'),
('5', '', '2', '', '', '2'),
('Oy tugashi bilan', '', 'Hisobot yili yakuni boК»yicha', '', '', 'Hisobot yili yakuni boК»yicha'),
('вЂњ4-sonli BHMSвЂќ orqali', '', 'Mahsulot(ish, xizmatlar)ni ishlab chiqarish va sotish xarajatlari tarkibi hamda moliyaviy natijalarni shakllantirish tartibi toК»gК»risidaвЂќgi Nizom orqali, вЂњ3-sonli BHMSвЂќ orqali', '', '', 'Mahsulot(ish, xizmatlar)ni ishlab chiqarish va sotish xarajatlari tarkibi hamda moliyaviy natijalarni shakllantirish tartibi toК»gК»risidaвЂќgi Nizom orqali, вЂњ3-sonli BHMSвЂќ orqali'),
('STF=UF вЂ“ DX + BD', '', 'STF=UF + FF вЂ“ FZ', '', '', 'STF=UF + FF вЂ“ FZ'),
('ikkiyoqlama yozish - buxgalteria hisobining oltin qoidasidir', '', 'ikkiyoqlama yozish usuli - bir xoК»jalik muomalasi  boК»yicha aynan bir xil summani buxgalteria hisobining ikki schyotida вЂ“ birining debeti va boshqasining kreditida aks etishidir', '', '', 'ikkiyoqlama yozish usuli - bir xoК»jalik muomalasi  boК»yicha aynan bir xil summani buxgalteria hisobining ikki schyotida вЂ“ birining debeti va boshqasining kreditida aks etishidir');
